---

- name: download icinga-php-library v{{ icingaweb_php_library }}.tar.gz
  delegate_to: localhost
  become: false
  get_url:
    url: https://github.com/Icinga/icinga-php-library/archive/v{{ icingaweb_php_library }}.tar.gz
    dest: "{{ icingaweb_local_tmp_directory }}/icinga-php-library-v{{ icingaweb_php_library }}.tar.gz"
    mode: 0660
  register: _download_artefact
  until: _download_artefact is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: deploy library archives
  copy:
    src: "{{ icingaweb_local_tmp_directory }}/icinga-php-library-v{{ icingaweb_php_library }}.tar.gz"
    dest: /tmp
    mode: 0700

- name: extract library archives
  unarchive:
    src: "/tmp/icinga-php-library-v{{ icingaweb_php_library }}.tar.gz"
    dest: /usr/share/icinga-php/
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0755
    remote_src: true

- name: create link from icinga-php-library to ipl
  file:
    src: "/usr/share/icinga-php/icinga-php-library-{{ icingaweb_php_library }}"
    dest: "/usr/share/icinga-php/ipl"
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0755
    state: link
    force: true
