---

mysql_python_package_debian: "{{ 'python3-mysqldb' if ansible_python.version.major == 3 else 'python-mysqldb' }}"

mysql_innodb_buffer_pool_size: 64M
mysql_innodb_log_file_size: 48M
mysql_innodb_lock_wait_timeout: 100

mysql_bind_address: 0.0.0.0
mysql_max_connections: 20

mysql_root_password_update: true

mysql_databases:
  - name: icinga2_ido
  - name: icingaweb_config

mysql_users:
  - name: icinga2_ido
    host: "%"
    password: icinga2
    priv: "icinga2_ido.*:ALL"
  - name: icingaweb_config
    host: "%"
    password: icingaweb_config
    priv: "icingaweb_config.*:ALL"
