---

# TODO
# drop python2 support!
# add assert

# - name: assert python version
#   assert:
#     that: ansible_python.version.major != 2
#     msg: "Sorry, we don't support python 2 anymore!"

- name: create local temp directory
  become: false
  delegate_to: 127.0.0.1
  file:
    path: "{{ icingaweb_local_tmp_directory }}"
    state: directory
    mode: 0755

- name: get version of installed php-fpm
  package_version:
    package_name: "php-fpm"
  register: package_version

- name: define php version
  set_fact:
    php_version: "{{ package_version.version }}"
    php_package_version: "{{ package_version.version_compressed }}"
  when:
    - package_version is defined
    - package_version.version is defined
    - package_version.version_compressed is defined

- name: assert php_version
  assert:
    that: php_version is version_compare('7.0', '>=')
    msg: "This role only works with PHP >= 7.0 .. found: {{ php_version }}"

- name: merge dependencies between defaults and custom
  set_fact:
    icingaweb_dependencies: "{{ icingaweb_dependencies + icingaweb_packages }}"

- name: get database package name
  package_version:
    package_name: "mariadb-client-core"
  register: package_version

- name: remove mariadb-client-core from dependency list if it already installed
  set_fact:
    icingaweb_dependencies: "{{ icingaweb_dependencies | reject('search', 'default-mysql-client-core') | list }}"
  when:
    - package_version.version is defined

- name: merge dependencies between defaults and custom for enabled icingaweb modules
  set_fact:
    icingaweb_modules_enabled: "{{ icingaweb_defaults_modules_enabled + icingaweb_modules_enabled }}"

- name: merge icingaweb_groups configuration between defaults and custom
  set_fact:
    icingaweb_groups: "{{ icingaweb_defaults_groups |
      combine( icingaweb_groups, recursive=True ) }}"

- name: merge icingaweb_authentication configuration between defaults and custom
  set_fact:
    icingaweb_authentication: "{{ icingaweb_defaults_authentication |
      combine( icingaweb_authentication, recursive=True ) }}"

- name: merge icingaweb_resources configuration between defaults and custom
  set_fact:
    icingaweb_resources: "{{ icingaweb_defaults_resources |
      combine( icingaweb_resources, recursive=True ) }}"

# TODO
# move the PHP dependencies into the php role
# and check here only for the neededed packages
- name: merge PHP dependencies between defaults and custom
  set_fact:
    icingaweb_php_dependencies: "{{ icingaweb_php_dependencies + icingaweb_php_packages }}"

- name: install requirements
  package:
    name: "{{ icingaweb_dependencies + icingaweb_php_dependencies }}"
    state: present
