---

# TODO
# drop python2 support!
# add assert

- name: assert python version
  assert:
    that: ansible_python.version.major != 2
    msg: "Sorry, we don't support python 2 anymore!"

- name: create local temp directory
  become: false
  delegate_to: 127.0.0.1
  file:
    path: "{{ icingaweb_local_tmp_directory }}"
    state: directory
    mode: 0755

- name: get the rpm or apt package facts
  package_facts:
    manager: "auto"

- name: get php-fpm package name
  set_fact:
    php_package_name: "{{ ansible_facts.packages | list | select('match', '^php.*fpm') | list | sort | first }}"

- name: assert php_package_name
  assert:
    that: php_package_name | length != 0
    msg: "I can't found an installed php-fpm package :("

- name: define php version
  set_fact:
    php_version: "{{ ansible_facts.packages[php_package_name][0].version[0:3] }}"
  when:
    - ansible_os_family | lower == 'redhat'

# debian9 : version: 7.0.33-0+deb9u10 / => version: 1:7.0+49
#
- name: define php version
  set_fact:
    php_version: "{{ ansible_facts.packages[php_package_name][0].version.split(':')[1].split('+')[0] }}"
  when:
    - ansible_os_family | lower == 'debian'

- name: set php_package_version
  set_fact:
    php_package_version: "{{ php_version | replace('.','') }}"

- name: assert php_version
  assert:
    that: php_version is version_compare('7.0', '>=')
    msg: "This role only works with PHP >= 7.0 .. found: {{ php_version }}"

- name: merge dependencies between defaults and custom
  set_fact:
    icingaweb_dependencies: "{{ icingaweb_dependencies + icingaweb_packages }}"

- name: get database package name
  set_fact:
    data_package_name: "{{ ansible_facts.packages | list | select('match', '^mariadb-client-core.*') | list | sort }}"

- name: remove mariadb-client-core from dependency list if it already installed
  set_fact:
    icingaweb_dependencies: "{{ icingaweb_dependencies | reject('search', 'default-mysql-client-core') | list }}"
  when:
    - data_package_name | select('match', '^mariadb-client-core.*')

- name: merge dependencies between defaults and custom for enabled icingaweb modules
  set_fact:
    icingaweb_modules_enabled: "{{ icingaweb_modules_enabled_defaults + icingaweb_modules_enabled }}"

- name: merge icingaweb_authentication configuration between defaults and custom
  set_fact:
    icingaweb_authentication: "{{ icingaweb_authentication_defaults |
      combine( icingaweb_authentication, recursive=True ) }}"

- name: merge icingaweb_resources configuration between defaults and custom
  set_fact:
    icingaweb_resources: "{{ icingaweb_resources_defaults |
      combine( icingaweb_resources, recursive=True ) }}"

- name: merge PHP dependencies between defaults and custom
  set_fact:
    icingaweb_php_dependencies: "{{ icingaweb_php_dependencies + icingaweb_php_packages }}"

- name: install requirements
  package:
    name: "{{ icingaweb_dependencies + icingaweb_php_dependencies }}"
    state: present
