---

- hosts: instance
  any_errors_fatal: false
  environment:
    NETRC: ''

  pre_tasks:
    - block:
        - name: detect python3
          stat:
            path: /usr/bin/python3
          register: __stat_present_python3
          changed_when: not __stat_present_python3.stat.exists

        - name: set python3
          set_fact:
            ansible_python_interpreter: /usr/bin/python3
          when:
            - ansible_python.version.major == 2
            - __stat_present_python3.stat.exists

        - name: Gathering Facts now
          setup:
      when:
        - ansible_os_family | lower == 'debian'

  # pre_tasks:
  #   - debug:
  #       msg:
  #         - "os family            : {{ ansible_os_family }}"
  #         - "distribution         : {{ ansible_distribution }}"
  #         - "distribution version : {{ ansible_distribution_major_version }}"
  #         - "ansible version      : {{ ansible_version.full }}"
  #         - "python version       : {{ ansible_python.version.major }}"

  roles:
    - role: ansible-icingaweb2
