---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''
  vars:
    # ansible_python_interpreter: python3

    # icingaweb
    #
    icingaweb_external_modules:
      - audit:
        enabled: true
        name: audit
        src: https://github.com/Icinga/icingaweb2-module-audit.git
        version: v1.0.1
        configuration:
          log:
            # file / syslog / none
            type: file
            # ident = "web-ident"
            # facility = "authpriv"
            path: /var/log/icingaweb2/audit.log
          stream:
            # none / json
            format: json
            path: /var/log/icingaweb2/json.log

    icingaweb_themes:
      - unicorn:
        name: unicorn
        src: https://github.com/Mikesch-mp/icingaweb2-theme-unicorn.git
        version: v1.0.2
        image: { name: "unicorn.png", "url": "http://i.imgur.com/SCfMd.png" }
      - batman-dark:
        name: batman-dark
        src: https://github.com/jschanz/icingaweb2-theme-batman-dark.git
        version: v1.0.0

    icingaweb_themes_default: unicorn

  roles:
    - role: bodsch.icingaweb2
