---

- name: raw task to install python3
  hosts: all
  gather_facts: true

  pre_tasks:
    - block:
        - name: Install python3 for Ansible
          raw: test -e /usr/bin/python3 || (apt-get -y update && apt install -y python3)
          register: output
          changed_when:
            - output.stdout | length > 0

        - name: Install pip3 for Ansible
          raw: test -e /usr/bin/pip3 || (apt-get -y update && apt install -y  python3-pip)
          register: output
          changed_when:
            - output.stdout | length > 0
      when:
        - ansible_os_family | lower == 'debian'

- name: prepare all containers
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: update package cache
      package:
        update_cache: true

    - name: install netstat for archlinux and debian based
      package:
        name:
          - net-tools
          - iproute2
        state: present
      when:
        - ansible_os_family | lower in [ 'archlinux', 'debian' ]

    - block:
        - name: prepare for centos7 and python2
          package:
            name:
              - python-setuptools
            state: present
      when:
        - ansible_os_family | lower == 'redhat'
        - ansible_python.version.major | int == 2

    - debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

  roles:
    - role: monitoring-tools

- name: prepare database container
  hosts: database
  gather_facts: true

  roles:
    - role: apparmor
    - role: snapd
    - role: mariadb

- name: prepare instance container
  hosts: instance
  gather_facts: true

  roles:
    - role: nginx
    - role: php-fpm

# - name: prepare icinga2
#   hosts: icinga2
#   gather_facts: true
#
#   roles:
#     - role: icinga2

...
