---

- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

- name: prepare all containers
  hosts: all
  gather_facts: true

  roles:
    - role: monitoring-tools

  post_tasks:
    - debug:
        msg:
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

- name: prepare database container
  hosts: database
  gather_facts: true

  roles:
    - role: apparmor
    - role: snapd
    - role: mariadb

  post_tasks:
    - debug:
        msg:
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

- name: prepare instance container
  hosts: instance
  gather_facts: true

  roles:
    - role: nginx
    - role: php-fpm

  post_tasks:
    - debug:
        msg:
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

- name: prepare icinga2
  hosts: icinga2
  gather_facts: true

  roles:
    - role: icinga2

  post_tasks:
    - debug:
        msg:
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

...
