---

- name: raw task to install python3
  hosts: all
  gather_facts: true

  pre_tasks:
    - block:
        - name: Install python3 for Ansible
          raw: test -e /usr/bin/python3 || (apt-get -y update && apt install -y python3)
          register: output
          changed_when: output.stdout | length != 0

        - name: Install pip3 for Ansible
          raw: test -e /usr/bin/pip3 || (apt-get -y update && apt install -y  python3-pip)
          register: output
          changed_when: output.stdout | length != 0
      when:
        - ansible_os_family | lower == 'debian'

- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: update package cache
      package:
        update_cache: true

    - name: install netstat
      package:
        name:
          - net-tools
          - iproute2
        state: present
      when:
        - ansible_os_family | lower in [ 'archlinux', 'debian' ]

    - name: prepare for centos7 and python2
      package:
        name:
          - python-setuptools
          - python2-pip
        state: present
      when:
        - ansible_os_family | lower == 'redhat'
        - ansible_python.version.major | int == 2

    - debug:
        msg:
          - "os family            : {{ ansible_os_family }}"
          - "distribution         : {{ ansible_distribution }}"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}"

  roles:
    - role: apparmor
    - role: snapd
    - role: mariadb
    - role: nginx
    - role: php-fpm
