---

- name: php-fpm
  src: bodsch.ansible_php

- name: mariadb
  src: https://github.com/geerlingguy/ansible-role-mysql.git
  version: 3.3.0

- name: nginx
  src: https://github.com/geerlingguy/ansible-role-nginx.git
  version: 2.7.0
