---

monitoring_plugins_directory: /usr/lib/monitoring-plugins

icinga2_salt: 42T2fYT6kK0njvNMww8eWinBdEO5vh02xwC5qaNMMx77qNkYFE7bIxj5v291ajAW

icinga2_ha: false

icinga2_api:
  user:
    icinga2:
      password: S0mh1TuFJI
      permissions: '*'

    icingaweb:
      password: S0mh1TuFJI
      permissions:
        - "status/query"
        - "actions/*"
        - "objects/modify/*"
        - "objects/query/*"

icinga2_masters:
  icinga2:
    # type: primary
    ip: 10.11.0.2

icinga2_ido:
  user: icinga2_ido
  password: icinga2
  host: database
  cleanup:
    acknowledgements_age: 72h

icinga2_master_features_enabled:
  - checker
  - api
  - ido-mysql
  - mainlog
  - notification

icinga2_host_object:
  localhost:
    # endpoint_name: master-1.icinga.local
    # zone: master
    display_name: "{{ ansible_fqdn }}"
    import: generic-host
    address: '{{ ansible_default_ipv4.address }}'
    vars: |
      os = "Linux"
      dist = "{{ ansible_distribution }}"
      dist_ver = "{{ ansible_distribution_version }}"
      disks = {
        "disk /" = {
          disk_partitions = "/"
        }
      }
      services = [ "icinga2", "uptime", "memory" ]
      memory = true
