---

mariadb_python_package_debian: "{{ 'python3-mysqldb' if ansible_python.version.major == 3 else 'python-mysqldb' }}"

mariadb_innodb_buffer_pool_size: 64M
mariadb_innodb_log_file_size: 48M
mariadb_innodb_lock_wait_timeout: 100

mariadb_bind_address: 0.0.0.0
mariadb_max_connections: 20

mariadb_root_password_update: true

mariadb_databases:
  - name: icinga2_ido
  - name: icingaweb_config

mariadb_users:
  - name: icinga2_ido
    host: "%"
    password: icinga2
    priv: "icinga2_ido.*:ALL"
  - name: icingaweb_config
    host: "%"
    password: icingaweb_config
    priv: "icingaweb_config.*:ALL"
