---

- name: icingadb module
  block:
    - name: create directory for icingadb configuration
      become: true
      file:
        path: /etc/icingaweb2/modules/icingadb
        state: directory
        recurse: true
        owner: "{{ icingaweb_user }}"
        group: "{{ icingaweb_group }}"
        mode: 0755

    - name: create icingadb configuration
      become: true
      template:
        src: modules/icingadb/config.ini.j2
        dest: /etc/icingaweb2/modules/icingadb/config.ini
        owner: "{{ icingaweb_user }}"
        group: "{{ icingaweb_group }}"
        mode: 0666

    - name: create redis configuration
      become: true
      template:
        src: modules/icingadb/redis.ini.j2
        dest: /etc/icingaweb2/modules/icingadb/redis.ini
        owner: "{{ icingaweb_user }}"
        group: "{{ icingaweb_group }}"
        mode: 0666

    - name: create commandtransport configuration
      become: true
      template:
        src: modules/icingadb/commandtransports.ini.j2
        dest: /etc/icingaweb2/modules/icingadb/commandtransports.ini
        owner: "{{ icingaweb_user }}"
        group: "{{ icingaweb_group }}"
        mode: 0666
  when:
    - icingaweb_icingadb is defined
    - icingaweb_icingadb.module.enabled | default('false')

...
