---

# monitoring_plugins_directory: /usr/lib/monitoring-plugins

icinga2_salt: 42T2fYT6kK0njvNMww8eWinBdEO5vh02xwC5qaNMMx77qNkYFE7bIxj5v291ajAW

# icinga2_ha: false

icinga2_mode: master

icinga2_masters:
  icinga2:
    # type: primary
    # ip: 10.11.0.15

icinga2_api:
  user:
    root:
      password: foo
      permissions: '*'

    icinga2:
      password: S0mh1TuFJI
      permissions: '*'

    icingaweb:
      password: S0mh1TuFJI
      permissions:
        - "actions/*"
        - "objects/modify/*"
        - "objects/query/*"
        - "status/query"

    icingadb-web:
      password: S0mh1TuFJI
      permissions:
        - "actions/*"
        - "objects/modify/*"
        - "objects/query/*"
        - "status/query"

icinga2_ido:
  user: icinga2_ido
  password: icinga2
  host: database
  cleanup:
    acknowledgements_age: 12h
    hostchecks_age: 12h
    servicechecks_age: 12h

icinga2_master_features_enabled:
  - checker
  - api
  - ido-mysql
  - mainlog
  - notification
  - icingadb

icinga2_features:
  icingadb:
    active: true
    host: icingadb
    port: 6379

icinga2_host_object:
  localhost:
    # endpoint_name: master-1.icinga.local
    # zone: master
    display_name: "{{ ansible_fqdn }}"
    import: generic-host
    address: '{{ ansible_default_ipv4.address }}'
    vars: |
      os = "Linux"
      dist = "{{ ansible_distribution }}"
      dist_ver = "{{ ansible_distribution_version }}"
      disks = {
        "disk /" = {
          disk_partitions = "/"
        }
      }
      services = [ "icinga2", "uptime", "memory" ]
      memory = true
