---

icingaweb_log_level: WARN

icingaweb_resources:
  icingaweb:
    type: db
    db: mysql
    host: database
    port: 3306
    dbname: icingaweb_config
    username: icingaweb_config
    password: icingaweb_config
    prefix: icingaweb_
    charset: utf8
  icinga_ido:
    type: db
    db: mysql
    host: database
    port: 3306
    dbname: icinga2_ido
    username: icinga2_ido
    password: icinga2
    charset: utf8
  icingadb:
    type: db
    db: mysql
    host: database
    port: 3306
    dbname: "{{ icingadb_database.database }}"
    username: "{{ icingadb_database.user }}"
    password: "{{ icingadb_database.password }}"
    charset: utf8

icingaweb_auth_backend:
  database:
    host: database
    port: 3306
    dbname: icingaweb_config
    username: icingaweb_config
    password: icingaweb_config

icingaweb_commandtransport:
  master-1:
    transport: api
    host: icinga2
    port: 5665
    username: icingaweb
    password: S0mh1TuFJI

icingaweb_db_users:
  - admin:
    username: admin
    password: admin
    preferences:
      language: de_DE
      timezone: Europe/Berlin
      show_application_state_messages: false
      show_stacktraces: false
      show_benchmark: false
      auto_refresh: true
  - bodsch:
    username: bodsch
    password: xxx
  - dark:
    username: dark
    password: s3cur3
    active: false
    force: true

icingaweb_icingadb:
  module:
    enabled: true
    src: https://github.com/Icinga/icingadb-web
    version: v1.0.0-rc2
  commandtransports: "{{ icingaweb_commandtransport }}"
  redis:
    tls: false
    primary:
      host: icingadb
      port: 6379
    secondary: {}

...
