---

- name: snapd
  src: bodsch.snapd
  version: 1.2.2

- name: apparmor
  src: bodsch.apparmor
  version: 1.0.3

- name: php-fpm
  src: bodsch.php
  version: 2.2.0

- name: mariadb
  src: bodsch.mariadb
  version: 2.4.0

- name: nginx
  src: bodsch.nginx
  version: 0.21.1

# - name: monitoring-tools
#   src: bodsch.monitoring_plugins
#   version: 1.4.2
#
# - name: icinga2
#   src: bodsch.icinga2
#   version: 1.9.0

...
