---

- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: arch- / artixlinux
      when:
        - ansible_distribution | lower == 'archlinux' or
          ansible_os_family | lower == 'artix linux'
      block:
        - name: update pacman system
          ansible.builtin.command: |
            pacman --refresh --sync --sysupgrade --noconfirm

        - name: create depends service
          ansible.builtin.copy:
            mode: 0755
            dest: /etc/init.d/net
            content: |
              #!/usr/bin/openrc-run
              true
          when:
            - ansible_os_family | lower == 'artix linux'

    - name: update package cache
      become: true
      ansible.builtin.package:
        update_cache: true

    - name: environment
      ansible.builtin.debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

# - name: prepare all containers
#   hosts: all
#   gather_facts: true
#
#   roles:
#     - role: monitoring-tools

- name: prepare database container
  hosts: database
  gather_facts: true

  roles:
    - role: apparmor
    - role: snapd
    - role: mariadb

- name: prepare icingadb container
  hosts: icingadb
  gather_facts: true

  roles:
    - role: redis
    - role: icingadb

- name: prepare instance container
  hosts: instance
  gather_facts: true

  roles:
    - role: nginx
    - role: php-fpm

# - name: prepare icinga2 container
#   hosts: icinga2
#   gather_facts: true
#
#   roles:
#     - role: icinga2

...
